name: Update Graphics

on:
  schedule:
    # We'll run this weekly
    - cron:  '0 12 * * 1'
  workflow_dispatch:

jobs:
  runner-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: gtn-community-paper-2020
          environment-file: environment.yml
          python-version: 3.8
          mamba-version: "*"
          auto-activate-base: false
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: "Build Graphs"
        run: |
          cd src
          for i in {analyze_instructor_survey.ipynb,analyze_hub_training_events.ipynb,analyze_tiaas_data.ipynb}; do
            jupyter nbconvert "$i" --to python --output "$i.py"
            python "$i.py"
          done
